# Generated by Django 5.1.7 on 2025-03-25 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'meal'], name='api_rating_user_id_aee66a_idx'),
        ),
    ]
